Add wireless regdom support to finellictl

diff --git a/finellictl b/finellictl
--- a/finellictl
+++ b/finellictl
@@ -17,6 +17,11 @@ if [[ $# -eq 0 || $1 == -h || $1 == --help ]]; then
   echo
   echo "    $(basename "$0") timezone # set timezone interactively"
   echo "    $(basename "$0") timezone America/New_York # set given timezone"
+  echo "                              # common options: Europe/Rome"
+  echo "                              #                 Europe/London"
+  echo
+  echo "    $(basename "$0") wregdom US # set wireless regulatory country"
+  echo "                              # common options: IT, GB"
   exit 0
 fi
 
@@ -44,6 +49,10 @@ function write_settings() {
 
   local tz="$(timedatectl show -p Timezone | awk -F= '{print $2}')"
   sudo yq -i ".timezone = \"$tz\"" $SETTINGS_PATH
+
+  local wreg="$(grep '^WIRELESS_REGDOM="' /etc/conf.d/wireless-regdom |
+    awk -F\" '{print $2}')"
+  sudo yq -i ".wireless-regdom = \"$wreg\"" $SETTINGS_PATH
 }
 
 function set_timezone() {
@@ -62,8 +71,24 @@ function set_timezone() {
   write_settings
 }
 
+function set_wirelessregdom() {
+  if [[ $1 =~ ^[a-zA-Z]{2}$ ]]; then
+    sudo sed -i -E "s/^WIRELESS_REGDOM=\"[A-Z]{2}\"/WIRELESS_REGDOM=\"$1\"/" \
+      /etc/conf.d/wireless-regdom
+  else
+    echo >&2 "error: $1 does not appear to be a valid country code"
+    exit 1
+  fi
+
+  write_settings
+}
+
 if [[ $1 == timezone ]]; then
   set_timezone "$2"
+fi
+
+if [[ $1 == wregdom ]]; then
+  set_wirelessregdom "$2"
 fi
 
 exit 0
